# Generated by Django 5.0.1 on 2024-01-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxyapp", "0003_scrapeurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapeurl",
            name="active_url",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
