# Generated by Django 5.0.1 on 2024-01-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxyapp", "0004_scrapeurl_active_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitedPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("proxy_ip", models.GenericIPAddressField()),
                ("proxy_port", models.PositiveIntegerField()),
                ("visited_url", models.URLField()),
                ("content", models.TextField()),
            ],
        ),
    ]
