# Generated by Django 5.0.1 on 2024-01-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxyapp", "0005_visitedpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamingUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stream_url", models.URLField(unique=True)),
                (
                    "stream_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
